# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20190418_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
